// ============================================================
// Travel Lab - Mock Hotel Data
// ============================================================

const HOTELS = [
  {
    id: 1,
    name: "ホテル グランドパレス 東京",
    area: "東京",
    address: "東京都千代田区一ツ橋1-1-1",
    category: "シティホテル",
    stars: 5,
    rating: 4.7,
    reviewCount: 1842,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "parking", "onsen", "breakfast", "gym", "pool"],
    description: "皇居を望む最上の立地。東京の中心で格別のラグジュアリー体験を。",
    prices: {
      rakuten: { price: 28500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 27800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 29200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 31000, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 30500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 29800, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 31500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 32000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },
  {
    id: 2,
    name: "渋谷スカイビューホテル",
    area: "東京",
    address: "東京都渋谷区道玄坂2-24-1",
    category: "ビジネスホテル",
    stars: 4,
    rating: 4.3,
    reviewCount: 967,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "breakfast", "gym"],
    description: "渋谷スクランブルスクエア隣接。アクセス抜群のスマートステイ。",
    prices: {
      rakuten: { price: 14200, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 13500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 14800, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 15200, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 14500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 13900, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 15500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 16000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 3,
    name: "新宿ファーストクラスステイ",
    area: "東京",
    address: "東京都新宿区西新宿2-7-2",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.1,
    reviewCount: 2301,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "parking"],
    description: "新宿駅徒歩3分。コスパ最強のビジネス向けホテル。",
    prices: {
      rakuten: { price: 7800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 8200, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 7500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 8900, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 8500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 7900, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 9200, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 9500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },
  {
    id: 4,
    name: "浅草 和の宿 風雅",
    area: "東京",
    address: "東京都台東区浅草2-3-4",
    category: "旅館",
    stars: 4,
    rating: 4.6,
    reviewCount: 543,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "onsen", "breakfast"],
    description: "浅草の下町風情に包まれた純和風旅館。夕食は本格懐石料理。",
    prices: {
      rakuten: { price: 19800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 20500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 19200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 19500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 21000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 21500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },
  {
    id: 5,
    name: "東京ベイ マリーナホテル",
    area: "東京",
    address: "東京都江東区有明3-2-1",
    category: "リゾートホテル",
    stars: 5,
    rating: 4.5,
    reviewCount: 789,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "pool", "gym", "parking", "breakfast"],
    description: "東京湾を望むシービュールーム。プールとスパで癒しの時間を。",
    prices: {
      rakuten: { price: 32000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 31500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 33500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 30800, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 31200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 29800, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 34000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 34500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },
  {
    id: 6,
    name: "京都 嵐山 竹の宿",
    area: "京都",
    address: "京都府京都市右京区嵯峨天龍寺芒ノ馬場町",
    category: "旅館",
    stars: 5,
    rating: 4.9,
    reviewCount: 412,
    image: "assets/images/hotel_kyoto.png",
    amenities: ["wifi", "onsen", "breakfast", "parking"],
    description: "嵐山の竹林に佇む隠れ家旅館。全室露天風呂付きの贅沢な滞在。",
    prices: {
      rakuten: { price: 45000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 43500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 46000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 44500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 47000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 47500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },
  {
    id: 7,
    name: "京都四条 モダンステイ",
    area: "京都",
    address: "京都府京都市下京区四条通麩屋町東入ル",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.2,
    reviewCount: 1156,
    image: "assets/images/hotel_kyoto.png",
    amenities: ["wifi", "breakfast"],
    description: "四条河原町から徒歩5分。観光の拠点に最適なスタイリッシュホテル。",
    prices: {
      rakuten: { price: 10500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 9800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 10200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 11500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 11000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 9500, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 12000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 12500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 8,
    name: "大阪 道頓堀 ルーフトップホテル",
    area: "大阪",
    address: "大阪府大阪市中央区道頓堀1-7-21",
    category: "ブティックホテル",
    stars: 4,
    rating: 4.4,
    reviewCount: 832,
    image: "assets/images/hotel_osaka.png",
    amenities: ["wifi", "gym", "breakfast"],
    description: "道頓堀の賑わいを高みから楽しむルーフトップバー完備のホテル。",
    prices: {
      rakuten: { price: 16800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 15900, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 17200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 15500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 16000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 15200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 17500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 18000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 9,
    name: "沖縄 恩納村 オーシャンリゾート",
    area: "沖縄",
    address: "沖縄県国頭郡恩納村前兼久1490",
    category: "リゾートホテル",
    stars: 5,
    rating: 4.8,
    reviewCount: 2045,
    image: "assets/images/hotel_okinawa.png",
    amenities: ["wifi", "pool", "beach", "gym", "breakfast", "parking"],
    description: "エメラルドグリーンの海に面したプライベートビーチ付き5つ星リゾート。",
    prices: {
      rakuten: { price: 52000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 50500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 53500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 49800, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 51000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 48500, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 54000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 54500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 10,
    name: "北海道 ニセコ 白銀の宿",
    area: "北海道",
    address: "北海道虻田郡ニセコ町字ニセコ488",
    category: "旅館",
    stars: 4,
    rating: 4.6,
    reviewCount: 678,
    image: "assets/images/hotel_hokkaido.png",
    amenities: ["wifi", "onsen", "breakfast", "parking", "ski"],
    description: "世界最高の粉雪で有名なニセコ。スキーと温泉を同時に堪能。",
    prices: {
      rakuten: { price: 38000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 36500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 39500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: 35000, url: "https://www.booking.com/?aid=travlab", mealPlan: "2食付" },
      expedia: { price: 37500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "2食付" },
      agoda: { price: 34500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 40000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 40500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },

  // ── 横浜 ──────────────────────────────────────
  {
    id: 11,
    name: "横浜みなとみらい グランドホテル",
    area: "横浜",
    address: "神奈川県横浜市西区みなとみらい2-2-1",
    category: "シティホテル",
    stars: 5,
    rating: 4.6,
    reviewCount: 1243,
    image: "assets/images/hotel_yokohama.png",
    amenities: ["wifi", "pool", "gym", "breakfast", "parking"],
    description: "みなとみらいの夜景を一望。横浜港のきらめきに包まれた最上の滞在。",
    prices: {
      rakuten: { price: 24800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 23500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 25200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 22800, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 23900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 22500, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 26000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 26500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },
  {
    id: 12,
    name: "横浜中華街 ステイホテル",
    area: "横浜",
    address: "神奈川県横浜市中区山下町193",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.0,
    reviewCount: 876,
    image: "assets/images/hotel_yokohama.png",
    amenities: ["wifi", "breakfast"],
    description: "中華街すぐそば。本場の食文化と観光を満喫できる好立地ホテル。",
    prices: {
      rakuten: { price: 9800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 9200, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 10100, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 8900, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 9500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 8700, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 10500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 11000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 13,
    name: "横浜駅前 ビジネスイン",
    area: "横浜",
    address: "神奈川県横浜市西区高島2-19-12",
    category: "ビジネスホテル",
    stars: 3,
    rating: 3.9,
    reviewCount: 2104,
    image: "assets/images/hotel_yokohama.png",
    amenities: ["wifi", "parking"],
    description: "横浜駅東口から徒歩2分。新幹線・電車利用のビジネス出張に最適。",
    prices: {
      rakuten: { price: 6800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 6500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 7100, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 6300, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 6700, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 6200, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 7500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 7800, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },

  // ── 福岡 ──────────────────────────────────────
  {
    id: 14,
    name: "福岡 博多駅前 プレミアホテル",
    area: "福岡",
    address: "福岡県福岡市博多区博多駅前3-2-1",
    category: "シティホテル",
    stars: 4,
    rating: 4.5,
    reviewCount: 1567,
    image: "assets/images/hotel_fukuoka.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "博多駅から徒歩3分。九州観光・ビジネスの拠点として最高の立地。",
    prices: {
      rakuten: { price: 15800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 14900, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 16200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 14500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 15200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 14200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 17000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 17500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 15,
    name: "天神 キャナルシティホテル",
    area: "福岡",
    address: "福岡県福岡市中央区天神2-14-8",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.2,
    reviewCount: 988,
    image: "assets/images/hotel_fukuoka.png",
    amenities: ["wifi", "breakfast"],
    description: "天神・大名エリアの中心部。グルメ・ショッピングに歩いて行ける便利な立地。",
    prices: {
      rakuten: { price: 10200, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 9700, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 10500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 9400, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 9900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 9200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 11000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 11500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 16,
    name: "糸島 海辺の宿 凪",
    area: "福岡",
    address: "福岡県糸島市志摩桜井4728",
    category: "旅館",
    stars: 4,
    rating: 4.7,
    reviewCount: 389,
    image: "assets/images/hotel_fukuoka.png",
    amenities: ["wifi", "onsen", "breakfast", "parking", "beach"],
    description: "玄界灘を望む全室オーシャンビュー。新鮮な海の幸と天然温泉で癒しの一泊。",
    prices: {
      rakuten: { price: 28000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 27000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 29000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 27500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 30000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 30500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },

  // ── 箱根 ──────────────────────────────────────
  {
    id: 17,
    name: "箱根湯本 老舗温泉旅館 萬翆楼",
    area: "箱根",
    address: "神奈川県足柄下郡箱根町湯本茶屋191",
    category: "旅館",
    stars: 5,
    rating: 4.8,
    reviewCount: 724,
    image: "assets/images/hotel_hakone.png",
    amenities: ["wifi", "onsen", "breakfast", "parking"],
    description: "箱根湯本の老舗旅館。大浴場・露天風呂・貸切風呂を完備した本格温泉体験。",
    prices: {
      rakuten: { price: 35000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 33500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 36000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 34000, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 37500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 38000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },
  {
    id: 18,
    name: "仙石原 富士見の宿 凛風",
    area: "箱根",
    address: "神奈川県足柄下郡箱根町仙石原1244",
    category: "旅館",
    stars: 4,
    rating: 4.6,
    reviewCount: 512,
    image: "assets/images/hotel_hakone.png",
    amenities: ["wifi", "onsen", "breakfast", "parking"],
    description: "仙石原のすすき草原に隣接。富士山と芦ノ湖を望む絶景と天然温泉が自慢。",
    prices: {
      rakuten: { price: 22000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 21000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 22500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 21500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 23500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 24000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },
  {
    id: 19,
    name: "箱根強羅 モダン温泉ホテル",
    area: "箱根",
    address: "神奈川県足柄下郡箱根町強羅1300-432",
    category: "シティホテル",
    stars: 4,
    rating: 4.3,
    reviewCount: 667,
    image: "assets/images/hotel_hakone.png",
    amenities: ["wifi", "onsen", "breakfast", "gym"],
    description: "ケーブルカー強羅駅徒歩1分。モダンデザインと温泉を融合したスタイリッシュホテル。",
    prices: {
      rakuten: { price: 18500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 17800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 19000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 17500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 18000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 17200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 20000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 20500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 大阪（追加） ──────────────────────────────
  {
    id: 20,
    name: "梅田 スカイタワーホテル",
    area: "大阪",
    address: "大阪府大阪市北区大淀中1-1-88",
    category: "シティホテル",
    stars: 4,
    rating: 4.4,
    reviewCount: 1392,
    image: "assets/images/hotel_osaka.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "大阪梅田の空中庭園展望台隣接。大阪市内を一望する高層フロアで特別な体験を。",
    prices: {
      rakuten: { price: 17500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 16800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 18000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 16200, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 16900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 15900, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 19000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 19500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 21,
    name: "なんば エコノミービジネスホテル",
    area: "大阪",
    address: "大阪府大阪市中央区千日前1-9-12",
    category: "ビジネスホテル",
    stars: 2,
    rating: 3.8,
    reviewCount: 3241,
    image: "assets/images/hotel_osaka.png",
    amenities: ["wifi"],
    description: "難波駅1分の超好立地。大阪観光の拠点に最適な格安ビジネスホテル。",
    prices: {
      rakuten: { price: 5200, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 4900, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 5500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 4700, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 5100, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 4600, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 5800, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 6200, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },

  // ── 京都（追加） ──────────────────────────────
  {
    id: 22,
    name: "祇園 和ダイニング旅館 花絵",
    area: "京都",
    address: "京都府京都市東山区祇園町南側570",
    category: "旅館",
    stars: 4,
    rating: 4.7,
    reviewCount: 298,
    image: "assets/images/hotel_kyoto.png",
    amenities: ["wifi", "breakfast", "onsen"],
    description: "祇園の石畳に面した数寄屋造りの旅館。舞妓さんの往来を窓越しに楽しめる贅沢な立地。",
    prices: {
      rakuten: { price: 32000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 30500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 33000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 31000, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 34000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 35000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 23,
    name: "京都駅前 ゲートウェイホテル",
    area: "京都",
    address: "京都府京都市下京区東塩小路町590",
    category: "シティホテル",
    stars: 4,
    rating: 4.3,
    reviewCount: 2087,
    image: "assets/images/hotel_kyoto.png",
    amenities: ["wifi", "breakfast", "parking"],
    description: "京都駅ビルに直結。東海道新幹線・近鉄・JR全路線利用に最高の利便性。",
    prices: {
      rakuten: { price: 13500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 12800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 14000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 12500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 13000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 12200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 15000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 15500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 沖縄（追加） ──────────────────────────────
  {
    id: 24,
    name: "石垣島 サンセットリゾート",
    area: "沖縄",
    address: "沖縄県石垣市新川1625-3",
    category: "リゾートホテル",
    stars: 5,
    rating: 4.9,
    reviewCount: 1124,
    image: "assets/images/hotel_okinawa.png",
    amenities: ["wifi", "pool", "beach", "breakfast", "parking"],
    description: "石垣島随一のサンセットスポットに立地。星空と海が織りなす絶景リゾート。",
    prices: {
      rakuten: { price: 58000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 56000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 60000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 54000, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 55500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 53000, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 62000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 62500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 25,
    name: "那覇国際通り ブティックホテル",
    area: "沖縄",
    address: "沖縄県那覇市牧志1-3-60",
    category: "ブティックホテル",
    stars: 3,
    rating: 4.2,
    reviewCount: 1876,
    image: "assets/images/hotel_okinawa.png",
    amenities: ["wifi", "breakfast"],
    description: "国際通り沿いの好立地。首里城・牧志公設市場へ徒歩圏内のスタイリッシュホテル。",
    prices: {
      rakuten: { price: 9500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 9000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 9800, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 8700, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 9200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 8500, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 10500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 11000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 26,
    name: "宮古島 コーラルビーチリゾート",
    area: "沖縄",
    address: "沖縄県宮古島市平良字西里856",
    category: "リゾートホテル",
    stars: 4,
    rating: 4.6,
    reviewCount: 743,
    image: "assets/images/hotel_okinawa.png",
    amenities: ["wifi", "pool", "beach", "breakfast", "parking"],
    description: "宮古島の透明度世界トップクラスの海が目の前。ダイビングやシュノーケルの聖地。",
    prices: {
      rakuten: { price: 38000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 36500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 39500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 35500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 37000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 35000, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 41000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 41500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 北海道（追加） ────────────────────────────
  {
    id: 27,
    name: "札幌 大通り公園ホテル",
    area: "北海道",
    address: "北海道札幌市中央区大通西3-7",
    category: "シティホテル",
    stars: 4,
    rating: 4.4,
    reviewCount: 1789,
    image: "assets/images/hotel_hokkaido.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "大通り公園に面した絶好のロケーション。テレビ塔・すすきのへ徒歩圏内。",
    prices: {
      rakuten: { price: 16500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 15800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 17000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 15200, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 15900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 14900, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 18000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 18500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 28,
    name: "函館ベイビュー 和洋旅館",
    area: "北海道",
    address: "北海道函館市若松町12-6",
    category: "旅館",
    stars: 4,
    rating: 4.5,
    reviewCount: 892,
    image: "assets/images/hotel_hokkaido.png",
    amenities: ["wifi", "onsen", "breakfast", "parking"],
    description: "日本三大夜景の函館山を望む旅館。函館朝市まで徒歩5分の好立地。",
    prices: {
      rakuten: { price: 24000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 23000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 25000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 23500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 26000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 26500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },
  {
    id: 29,
    name: "富良野 ラベンダーフィールドリゾート",
    area: "北海道",
    address: "北海道空知郡富良野市北の峰町18-18",
    category: "リゾートホテル",
    stars: 4,
    rating: 4.5,
    reviewCount: 601,
    image: "assets/images/hotel_hokkaido.png",
    amenities: ["wifi", "onsen", "breakfast", "parking", "ski"],
    description: "ラベンダー畑に囲まれた北海道の大自然リゾート。冬はスキー、夏は大自然満喫。",
    prices: {
      rakuten: { price: 26000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 24800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 27000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: 24000, url: "https://www.booking.com/?aid=travlab", mealPlan: "2食付" },
      expedia: { price: 25000, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "2食付" },
      agoda: { price: 23500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 28500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 29000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },

  // ── 名古屋 ──────────────────────────────────
  {
    id: 30,
    name: "名古屋城前 グランドホテル",
    area: "名古屋",
    address: "愛知県名古屋市中区三の丸1-1-1",
    category: "シティホテル",
    stars: 4,
    rating: 4.4,
    reviewCount: 1102,
    image: "assets/images/hotel_nagoya.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "名古屋城のすぐそば。名古屋めし・観光・ビジネスに最高の拠点ホテル。",
    prices: {
      rakuten: { price: 14800, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 14000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 15200, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 13500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 14200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 13200, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 16000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 16500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 31,
    name: "栄 ビジネスプレミアホテル",
    area: "名古屋",
    address: "愛知県名古屋市中区錦3-14-15",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.1,
    reviewCount: 2456,
    image: "assets/images/hotel_nagoya.png",
    amenities: ["wifi", "breakfast"],
    description: "栄・矢場町エリアの中心部。名古屋テレビ塔やオアシス21が徒歩圏内。",
    prices: {
      rakuten: { price: 8500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 8000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 8800, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 7700, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 8200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 7600, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 9500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 10000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 神戸 ──────────────────────────────────────
  {
    id: 32,
    name: "神戸ポートピア ハーバービューホテル",
    area: "神戸",
    address: "兵庫県神戸市中央区港島中町6-10-1",
    category: "シティホテル",
    stars: 5,
    rating: 4.5,
    reviewCount: 978,
    image: "assets/images/hotel_kobe.png",
    amenities: ["wifi", "pool", "breakfast", "gym", "parking"],
    description: "神戸港を一望する5つ星シティリゾート。神戸ポートライナーで空港直結。",
    prices: {
      rakuten: { price: 22000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 21000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 22800, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 20500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 21500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 20000, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 24000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 24500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 33,
    name: "北野 異人館ブティックホテル",
    area: "神戸",
    address: "兵庫県神戸市中央区北野町3-6-18",
    category: "ブティックホテル",
    stars: 4,
    rating: 4.6,
    reviewCount: 423,
    image: "assets/images/hotel_kobe.png",
    amenities: ["wifi", "breakfast"],
    description: "神戸北野の異人館街に佇む全18室の隠れ家ホテル。異国情緒あふれる空間。",
    prices: {
      rakuten: { price: 18500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 17800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 19000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 17000, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 17500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 16800, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 20000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 20500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 奈良 ──────────────────────────────────────
  {
    id: 34,
    name: "奈良公園 鹿の宿 やまと",
    area: "奈良",
    address: "奈良県奈良市高畑町1096",
    category: "旅館",
    stars: 4,
    rating: 4.6,
    reviewCount: 534,
    image: "assets/images/hotel_nara.png",
    amenities: ["wifi", "breakfast", "onsen", "parking"],
    description: "奈良公園の鹿が出迎える老舗旅館。東大寺・春日大社へ徒歩圏内の最高の立地。",
    prices: {
      rakuten: { price: 20000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "2食付" },
      jalan: { price: 19000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "2食付" },
      yahoo: { price: 20500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "2食付" },
      booking: { price: null, url: null, mealPlan: null },
      expedia: { price: null, url: null, mealPlan: null },
      agoda: { price: 19500, url: "https://www.agoda.com/?tl=1", mealPlan: "2食付" },
      jtb: { price: 22000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "2食付" },
      rurubu: { price: 22500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "2食付" },
    },
  },

  // ── 軽井沢 ──────────────────────────────────
  {
    id: 35,
    name: "軽井沢 高原リゾートホテル 白樺",
    area: "軽井沢",
    address: "長野県北佐久郡軽井沢町軽井沢1323",
    category: "リゾートホテル",
    stars: 4,
    rating: 4.5,
    reviewCount: 812,
    image: "assets/images/hotel_karuizawa.png",
    amenities: ["wifi", "onsen", "breakfast", "gym", "parking"],
    description: "白樺林に囲まれた高原リゾート。旧軽銀座・プリンスアウトレットへ無料シャトル運行。",
    prices: {
      rakuten: { price: 25000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 24000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 25800, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 23000, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 24200, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 22800, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 27000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 27500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 仙台 ──────────────────────────────────────
  {
    id: 36,
    name: "仙台 一番町 プレミアスイート",
    area: "仙台",
    address: "宮城県仙台市青葉区一番町4-6-1",
    category: "シティホテル",
    stars: 4,
    rating: 4.3,
    reviewCount: 1234,
    image: "assets/images/hotel_sendai.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "杜の都仙台の中心部。牛タン・ずんだを楽しみながら宮城の観光に最適。",
    prices: {
      rakuten: { price: 13500, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 12800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 14000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 12200, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 12900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 12000, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 15000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 15500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 広島 ──────────────────────────────────────
  {
    id: 37,
    name: "広島平和公園 ガーデンホテル",
    area: "広島",
    address: "広島県広島市中区大手町1-5-3",
    category: "シティホテル",
    stars: 4,
    rating: 4.4,
    reviewCount: 1567,
    image: "assets/images/hotel_hiroshima.png",
    amenities: ["wifi", "breakfast", "parking"],
    description: "平和記念公園まで徒歩5分。宮島・原爆ドーム観光の拠点として最適なホテル。",
    prices: {
      rakuten: { price: 12000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 11500, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 12500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 11000, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 11800, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 10800, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 13500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 14000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },

  // ── 東京（追加） ──────────────────────────────
  {
    id: 38,
    name: "銀座 ラグジュアリーコレクション",
    area: "東京",
    address: "東京都中央区銀座8-8-8",
    category: "シティホテル",
    stars: 5,
    rating: 4.8,
    reviewCount: 623,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "gym", "breakfast", "pool"],
    description: "銀座の中心に佇く最上のラグジュアリーホテル。全室スイートの極上ステイ。",
    prices: {
      rakuten: { price: 65000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "素泊まり" },
      jalan: { price: 63000, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "素泊まり" },
      yahoo: { price: 67000, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "素泊まり" },
      booking: { price: 61000, url: "https://www.booking.com/?aid=travlab", mealPlan: "素泊まり" },
      expedia: { price: 62500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "素泊まり" },
      agoda: { price: 60000, url: "https://www.agoda.com/?tl=1", mealPlan: "素泊まり" },
      jtb: { price: 68000, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "素泊まり" },
      rurubu: { price: 70000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "素泊まり" },
    },
  },
  {
    id: 39,
    name: "秋葉原 テックホテル",
    area: "東京",
    address: "東京都千代田区外神田4-7-3",
    category: "ビジネスホテル",
    stars: 3,
    rating: 4.0,
    reviewCount: 1843,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "breakfast"],
    description: "電気街・アキバへ歩いてすぐ。秋葉原・神田・上野観光に便利な好立地ホテル。",
    prices: {
      rakuten: { price: 8200, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 7800, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 8500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 7500, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 7900, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 7400, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 9200, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 9500, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
  {
    id: 40,
    name: "品川 シーサイドスイーツホテル",
    area: "東京",
    address: "東京都港区港南2-16-1",
    category: "シティホテル",
    stars: 4,
    rating: 4.2,
    reviewCount: 1102,
    image: "assets/images/hotel_tokyo.png",
    amenities: ["wifi", "breakfast", "gym", "parking"],
    description: "品川駅直結。羽田空港20分・東京駅10分。出張・旅行どちらにも最適なアクセス。",
    prices: {
      rakuten: { price: 18000, url: "https://travel.rakuten.co.jp/?af=travlab", mealPlan: "朝食付" },
      jalan: { price: 17200, url: "https://www.jalan.net/?sc_cid=travlab", mealPlan: "朝食付" },
      yahoo: { price: 18500, url: "https://travel.yahoo.co.jp/?travlab=1", mealPlan: "朝食付" },
      booking: { price: 16800, url: "https://www.booking.com/?aid=travlab", mealPlan: "朝食付" },
      expedia: { price: 17500, url: "https://www.expedia.co.jp/?tl=1", mealPlan: "朝食付" },
      agoda: { price: 16500, url: "https://www.agoda.com/?tl=1", mealPlan: "朝食付" },
      jtb: { price: 19500, url: "https://www.jtb.co.jp/?tl=1", mealPlan: "朝食付" },
      rurubu: { price: 20000, url: "https://www.rurubu.travel/?tl=1", mealPlan: "朝食付" },
    },
  },
];

// Helper: get minimum price for a hotel
function getMinPrice(hotel) {
  const prices = Object.values(hotel.prices)
    .filter(p => p.price !== null)
    .map(p => p.price);
  return Math.min(...prices);
}

// Helper: get which site has minimum price
function getCheapestSite(hotel) {
  let minSite = null;
  let minPrice = Infinity;
  for (const [site, data] of Object.entries(hotel.prices)) {
    if (data.price !== null && data.price < minPrice) {
      minPrice = data.price;
      minSite = site;
    }
  }
  return minSite;
}

// Helper: amenity icon mapping
const AMENITY_ICONS = {
  wifi: { icon: "📶", label: "Wi-Fi" },
  parking: { icon: "🅿️", label: "駐車場" },
  onsen: { icon: "♨️", label: "温泉" },
  breakfast: { icon: "🍽️", label: "朝食" },
  gym: { icon: "💪", label: "ジム" },
  pool: { icon: "🏊", label: "プール" },
  beach: { icon: "🏖️", label: "ビーチ" },
  ski: { icon: "⛷️", label: "スキー" },
};

// Site display config
const SITE_CONFIG = {
  rakuten: { name: "楽天トラベル", color: "#bf0000", bgColor: "#fff0f0", logo: "楽天" },
  jalan: { name: "じゃらん", color: "#e85d00", bgColor: "#fff5f0", logo: "じゃらん" },
  yahoo: { name: "Yahoo!トラベル", color: "#720096", bgColor: "#f8f0ff", logo: "Yahoo!" },
  booking: { name: "Booking.com", color: "#003580", bgColor: "#f0f4ff", logo: "Booking" },
  expedia: { name: "Expedia", color: "#000080", bgColor: "#f0f4ff", logo: "Expedia" },
  agoda: { name: "Agoda", color: "#c72228", bgColor: "#fff0f0", logo: "Agoda" },
  jtb: { name: "JTB", color: "#cc0000", bgColor: "#fff0f0", logo: "JTB" },
  rurubu: { name: "るるぶトラベル", color: "#eb6100", bgColor: "#fff5f0", logo: "るるぶ" },
};
